COM**************
COM Poter broyles
COM www.caattsolutions.com
COM 7/15/13
COM**************

COM**************
COM Demonstrating the use of how the basic dialog box can be used to 
COM transfer variables from project to project.
COM
COM This should be usable within Audit Exchange
COM**************

 DO va01_demo_dataonly

COM************* 
COM Demonstrating the use of how the basic dialog box can be used to 
COM query the data
COM
COM This should be usable within Audit Exchange
COM*************

 DO vb01_demo_dataquery

COM***********
COM END AA01
COM***********

